# Generated by Django 2.0.6 on 2018-09-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='text',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
